import { Inter } from 'next/font/google';
import '../style/globals.css';
import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';
import AlertProvider from '@/components/AlertProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: "Дай п'ять",
	// description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AlertProvider>
					<Navbar />
					{children}
					<Footer />
				</AlertProvider>
			</body>
		</html>
	);
}
